import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BackgroundBoxesDemo } from "./Test/BackgroundBoxesDemo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen w-full">
          {/* Background effect */}
          <BackgroundBoxesDemo />

          {/* Page content */}
          <main className="relative z-30">{children}</main>
        </div>
      </body>
    </html>
  );
}
